name: Run Insta Telegram Bot

on:
  workflow_dispatch:  # Manually run from GitHub UI
  schedule:
    - cron: '15 7 * * *'   # Run daily at 07:15 UTC
    - cron: '37 16 * * *'  # Run daily at 16:37 UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install instapy telegram python-telegram-bot schedule

      - name: Run InstaPy Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python isp.py
          
